# String Manipulation in Python
a = "everyday is a new day to shine"
print(a[2:5])
print(a[-5:-2])
print(a[0:10:2])
print(a[::-1])
print(a.capitalize())
print(a.title())
print(a.upper())
print(a.lower())
print(a.strip())
print(a.replace("day", "moment"))
print(a.split(" "))
print(a.find("new"))
print(a.count("a"))
print(a.startswith("everyday"))
print(a.endswith("shine"))
print(len(a))
print(a.index("shine"))
print(a.islower())
print(a.isupper())
print(a.isalpha())
print(a.isdigit())
print(a.isalnum())
print(a.center(50))
print(a.ljust(50))
print(a.rjust(50))
print(a.zfill(60))
print(a.swapcase())
print(a.partition("new"))
print(a.rpartition("day"))
print(a.encode())
print(a.format())
print(a.format_map({"day": "moment"}))
print(a.translate(str.maketrans("day", "mom")))
print(a.removeprefix("everyday "))
print(a.removesuffix(" to shine"))
print(a.casefold())
print(a.expandtabs())
print(a.isprintable())
print(a.join(["Hello", "World"]))
print(a.splitlines())
print(a.rsplit(" "))
print(a.startswith("every"))
print(a.endswith("shine"))
print(a.replace("a", "o", 2))
print(a.count("e", 0, 10))
print(a.find("is", 0, 15))
print(a.index("new", 0, 20))
print(a.partition("is"))
print(a.rpartition("a"))
print(a.encode("utf-8"))
print(a.encode("ascii", "ignore"))
print(a.zfill(70))
print(a.lstrip("everyday "))